const TAG_RULES = [
  // Geografía / enfoque
  {
    tag: 'argentina',
    strongKeywords: ['argentina', 'argentino', 'argentina'],
    weakKeywords: ['caba', 'buenos aires', 'casa rosada'],
    phrases: ['republica argentina', 'ciudad de buenos aires'],
    excludePhrases: [],
    sections: ['politica', 'economia', 'finanzas', 'deportes', 'nacional'],
    regions: ['argentina'],
    minScore: 7,
  },
  {
    tag: 'latam',
    strongKeywords: ['brasil', 'mexico', 'uruguay', 'chile', 'colombia', 'venezuela'],
    weakKeywords: ['latinoamerica', 'sudamerica'],
    phrases: ['america latina'],
    excludePhrases: [],
    sections: ['mundo'],
    regions: ['latam'],
    minScore: 7,
  },
  {
    tag: 'europa',
    strongKeywords: ['union europea', 'europa', 'francia', 'alemania', 'espana', 'italia', 'polonia'],
    weakKeywords: ['bruselas'],
    phrases: ['union europea'],
    excludePhrases: [],
    sections: ['mundo'],
    regions: ['europa'],
    minScore: 7,
  },
  {
    tag: 'eeuu',
    strongKeywords: ['eeuu', 'estados unidos', 'wall street', 'pentagono', 'reserva federal'],
    weakKeywords: ['fed', 'texas', 'washington'],
    phrases: ['estados unidos'],
    excludePhrases: [],
    sections: ['mundo', 'finanzas', 'tecnologia'],
    regions: ['eeuu'],
    minScore: 7,
  },

  // Tecnología
  {
    tag: 'ia',
    strongKeywords: ['inteligencia artificial', 'modelo de lenguaje', 'openai', 'anthropic', 'chatgpt', 'claude', 'gemini'],
    weakKeywords: ['ia', 'algoritmo generativo'],
    phrases: ['inteligencia artificial', 'modelo de lenguaje'],
    excludePhrases: [],
    sections: ['tecnologia'],
    minScore: 6,
  },
  {
    tag: 'openai',
    strongKeywords: ['openai'],
    weakKeywords: [],
    phrases: [],
    excludePhrases: [],
    sections: ['tecnologia'],
    minScore: 6,
  },
  {
    tag: 'anthropic',
    strongKeywords: ['anthropic', 'claude'],
    weakKeywords: [],
    phrases: [],
    excludePhrases: [],
    sections: ['tecnologia'],
    minScore: 6,
  },
  {
    tag: 'microsoft',
    strongKeywords: ['microsoft', 'windows', 'azure'],
    weakKeywords: ['office'],
    phrases: [],
    excludePhrases: [],
    sections: ['tecnologia'],
    minScore: 6,
  },
  {
    tag: 'google',
    strongKeywords: ['google', 'android', 'pixel', 'chrome'],
    weakKeywords: [],
    phrases: [],
    excludePhrases: [],
    sections: ['tecnologia'],
    minScore: 6,
  },
  {
    tag: 'amazon',
    strongKeywords: ['amazon', 'aws'],
    weakKeywords: [],
    phrases: [],
    excludePhrases: [],
    sections: ['tecnologia', 'negocios'],
    minScore: 6,
  },
  {
    tag: 'empresas',
    strongKeywords: ['empresa', 'empresas', 'corporacion', 'multinacional', 'ejecutivos'],
    weakKeywords: ['lanzamientos', 'nombramientos', 'negocios', 'inversiones'],
    phrases: ['noticias de empresas', 'acuerdo de exclusividad'],
    excludePhrases: [],
    sections: ['negocios', 'tecnologia'],
    minScore: 6,
  },

  // Economía / finanzas
  {
    tag: 'dolar',
    strongKeywords: ['dolar', 'dolar blue', 'dolar oficial', 'devaluacion'],
    weakKeywords: ['mep', 'ccl', 'tipo de cambio', 'brecha cambiaria'],
    phrases: ['dolar blue', 'dolar oficial', 'tipo de cambio'],
    excludePhrases: [],
    sections: ['economia', 'finanzas'],
    regions: ['argentina'],
    minScore: 6,
  },
  {
    tag: 'reservas',
    strongKeywords: ['reservas', 'bcra'],
    weakKeywords: ['banco central'],
    phrases: ['reservas del banco central'],
    excludePhrases: [],
    sections: ['economia', 'finanzas'],
    regions: ['argentina'],
    minScore: 6,
  },
  {
    tag: 'inflacion',
    strongKeywords: ['inflacion', 'ipc'],
    weakKeywords: ['precios', 'interanual', 'mensual'],
    phrases: ['indice de precios', 'canasta basica'],
    excludePhrases: [],
    sections: ['economia', 'finanzas'],
    regions: ['argentina'],
    minScore: 6,
  },
  {
    tag: 'mercados',
    strongKeywords: ['wall street', 'mercados', 'bonos', 'acciones', 'activos'],
    weakKeywords: ['riesgo pais', 'fed', 'bajas', 'subas'],
    phrases: ['activos argentinos', 'riesgo pais', 'reserva federal'],
    excludePhrases: [],
    sections: ['finanzas', 'economia'],
    minScore: 6,
  },
  {
    tag: 'deuda',
    strongKeywords: ['bonos', 'deuda', 'riesgo pais'],
    weakKeywords: ['wall street'],
    phrases: ['riesgo pais'],
    excludePhrases: [],
    sections: ['finanzas', 'economia'],
    minScore: 6,
  },
  {
    tag: 'criptomonedas',
    strongKeywords: ['bitcoin', 'ethereum', 'criptomonedas', 'cripto'],
    weakKeywords: ['etf spot', 'etf', 'tokens'],
    phrases: ['resto de las criptomonedas'],
    excludePhrases: [],
    sections: ['finanzas', 'tecnologia'],
    minScore: 6,
  },
  {
    tag: 'creditos',
    strongKeywords: ['credito', 'creditos', 'hipotecarios', 'prestamos'],
    weakKeywords: ['financiacion', 'corrida'],
    phrases: ['credito privado', 'creditos hipotecarios'],
    excludePhrases: [],
    sections: ['finanzas', 'economia', 'real-estate'],
    minScore: 6,
  },
  {
    tag: 'vivienda',
    strongKeywords: ['vivienda', 'hipotecarios', 'propiedades', 'inmuebles'],
    weakKeywords: ['primera vivienda', 'hipoteca'],
    phrases: ['primera vivienda', 'instituto de vivienda'],
    excludePhrases: [],
    sections: ['real-estate', 'economia', 'politica'],
    minScore: 6,
  },
  {
    tag: 'empleo',
    strongKeywords: ['empleo', 'trabajo', 'laboral', 'gremio', 'sindicato', 'paritaria'],
    weakKeywords: ['mercado laboral', 'salarios', 'demanda laboral'],
    phrases: ['conciliacion obligatoria', 'mercado laboral'],
    excludePhrases: [],
    sections: ['economia', 'negocios', 'politica'],
    regions: ['argentina'],
    minScore: 6,
  },
  {
    tag: 'impuestos',
    strongKeywords: ['impuesto', 'impuestos', 'arca', 'afip', 'tributaria'],
    weakKeywords: ['fiscal', 'bienes personales'],
    phrases: ['impuesto a las ganancias', 'bienes personales', 'declaraciones juradas'],
    excludePhrases: [],
    sections: ['economia', 'finanzas'],
    regions: ['argentina'],
    minScore: 6,
  },
  {
    tag: 'jubilaciones',
    strongKeywords: ['anses', 'jubilacion', 'jubilado', 'pension'],
    weakKeywords: ['obra social'],
    phrases: ['comprobante de obra social'],
    excludePhrases: [],
    sections: ['economia', 'nacional'],
    regions: ['argentina'],
    minScore: 6,
  },
  {
    tag: 'energia',
    strongKeywords: ['petroleo', 'gas', 'energia', 'combustible', 'crudo'],
    weakKeywords: ['petroleras', 'suministro', 'red electrica'],
    phrases: ['infraestructura energetica', 'complejos petroleros', 'instalaciones petroleras'],
    excludePhrases: [],
    sections: ['energia', 'economia', 'finanzas', 'mundo'],
    minScore: 6,
  },
  {
    tag: 'comercio internacional',
    strongKeywords: ['aranceles', 'importacion', 'importaciones', 'exportacion', 'exportaciones', 'mercosur'],
    weakKeywords: ['union europea', 'comercio exterior'],
    phrases: ['mercosur union europea', 'comercio exterior'],
    excludePhrases: [],
    sections: ['economia', 'mundo', 'energia'],
    minScore: 6,
  },
  {
    tag: 'mercosur',
    strongKeywords: ['mercosur'],
    weakKeywords: ['union europea'],
    phrases: ['acuerdo mercosur union europea'],
    excludePhrases: [],
    sections: ['mundo', 'economia', 'politica'],
    minScore: 6,
  },
  {
    tag: 'recesion',
    strongKeywords: ['recesion', 'default'],
    weakKeywords: ['caida de actividad', 'deterioro'],
    phrases: ['riesgo de recesion'],
    excludePhrases: [],
    sections: ['economia', 'finanzas'],
    minScore: 6,
  },
  {
    tag: 'plazo fijo',
    strongKeywords: ['plazo fijo', 'tasas hoy', 'rendimientos bancarios'],
    weakKeywords: ['ahorrista', 'tasa nominal', 'tasa efectiva'],
    phrases: ['plazo fijo', 'tasas bancarias'],
    excludePhrases: [],
    sections: ['economia', 'finanzas'],
    regions: ['argentina'],
    minScore: 6,
  },
  {
    tag: 'cuenta dni',
    strongKeywords: ['cuenta dni', 'banco provincia'],
    weakKeywords: ['billetera digital', 'pagos sin contacto'],
    phrases: ['pagos sin contacto', 'banco provincia'],
    excludePhrases: [],
    sections: ['economia', 'finanzas'],
    regions: ['argentina'],
    minScore: 6,
  },
  {
    tag: 'superavit',
    strongKeywords: ['superavit', 'superavit fiscal', 'recaudacion'],
    weakKeywords: ['privatizaciones', 'fiscal'],
    phrases: ['superavit fiscal', 'desplome de la recaudacion'],
    excludePhrases: [],
    sections: ['economia', 'finanzas'],
    minScore: 6,
  },

  // Política / justicia ARG
  {
    tag: 'politica',
    strongKeywords: ['gobierno', 'congreso', 'senado', 'diputados', 'presidente', 'ministro', 'oposicion'],
    weakKeywords: ['casa rosada', 'ejecutivo', 'pliegos', 'diputada', 'funcion publica'],
    phrases: ['poder ejecutivo', 'camara alta', 'camara de diputados'],
    excludePhrases: [],
    sections: ['politica', 'nacional', 'mundo'],
    regions: ['argentina', 'latam'],
    minScore: 6,
  },
  {
    tag: 'politica argentina',
    strongKeywords: ['milei', 'adorni', 'bullrich', 'caputo', 'cfk', 'cristina kirchner', 'massa', 'macri', 'kicillof'],
    weakKeywords: ['casa rosada', 'senado', 'diputados'],
    phrases: ['javier milei', 'karina milei', 'manuel adorni'],
    excludePhrases: [],
    sections: ['politica', 'nacional'],
    regions: ['argentina'],
    minScore: 6,
  },
  {
    tag: 'milei',
    strongKeywords: ['milei', 'javier milei', 'karina milei'],
    weakKeywords: ['presidente'],
    phrases: ['entorno presidencial'],
    excludePhrases: [],
    sections: ['politica'],
    regions: ['argentina'],
    minScore: 6,
  },
  {
    tag: 'justicia',
    strongKeywords: ['justicia', 'juicio', 'fiscal', 'denuncia', 'denuncian', 'causa', 'licitaciones'],
    weakKeywords: ['tribunal', 'indagatoria', 'se nego a declarar', 'arresto domiciliario'],
    phrases: ['conflicto de intereses', 'se nego a declarar', 'bajo la lupa'],
    excludePhrases: [],
    sections: ['politica', 'mundo', 'nacional', 'entretenimiento'],
    minScore: 6,
  },
  {
    tag: 'seguridad',
    strongKeywords: ['policia', 'desalojo', 'fuerzas de seguridad'],
    weakKeywords: ['manifestantes', 'custodia'],
    phrases: ['fuerzas de seguridad'],
    excludePhrases: [],
    sections: ['politica', 'nacional'],
    minScore: 6,
  },
  {
    tag: 'protesta',
    strongKeywords: ['manifestantes', 'reclamo', 'carpa', 'gremio'],
    weakKeywords: ['pagos adeudados', 'desalojo'],
    phrases: ['plaza de mayo', 'conciliacion obligatoria'],
    excludePhrases: [],
    sections: ['politica', 'nacional', 'negocios'],
    minScore: 6,
  },

  // Internacional
  {
    tag: 'guerra',
    strongKeywords: ['iran', 'israel', 'bombardeo', 'misiles', 'ofensiva', 'ataques'],
    weakKeywords: ['teheran', 'petroleras', 'eeuu', 'petroleo'],
    phrases: ['medio oriente', 'golfo persico', 'estrecho de ormuz', 'complejos petroleros', 'infraestructura energetica'],
    excludePhrases: ['guerra de pop stars', 'guerra de fans', 'guerra de ratings', 'guerra mediatica', 'guerra por la copa'],
    sections: ['mundo', 'finanzas', 'deportes'],
    regions: ['medio-oriente'],
    minScore: 7,
  },

  // Fútbol / deportes ARG
  {
    tag: 'futbol',
    strongKeywords: ['futbol', 'afa', 'gol', 'entrenador', 'dt', 'seleccion', 'escudo'],
    weakKeywords: ['partido', 'torneo', 'club', 'copa', 'hinchas'],
    phrases: ['liga profesional', 'copa de africa', 'federacion senegalesa de futbol', 'martin palermo'],
    excludePhrases: ['club de los 100 mil millones', 'estrellas del futbol en una serie'],
    sections: ['deportes'],
    minScore: 6,
  },
  {
    tag: 'futbol argentino',
    strongKeywords: [
      'boca', 'river', 'san lorenzo', 'racing', 'independiente', 'huracan', 'velez', 'estudiantes',
      'gimnasia', 'rosario central', 'newells', 'talleres', 'belgrano', 'instituto', 'lanus', 'banfield',
      'defensa y justicia', 'argentinos juniors', 'platense', 'tigre', 'union', 'colon', 'godoy cruz',
      'sarmiento', 'barracas central', 'riestra', 'independiente rivadavia', 'xeneize', 'millonario',
      'bombonera', 'monumental', 'nuevo gasometro'
    ],
    weakKeywords: ['afa', 'liga profesional', 'copa argentina'],
    phrases: ['seleccion argentina', 'liga profesional', 'primera division argentina'],
    excludePhrases: ['uar', 'world rugby', 'rugby', 'los pumas', 'beisbol', 'super bowl', 'surf nacional'],
    sections: ['deportes'],
    minScore: 8,
  },
  {
    tag: 'rugby',
    strongKeywords: ['rugby', 'uar', 'world rugby'],
    weakKeywords: ['mundial 2035'],
    phrases: ['copa del mundo'],
    excludePhrases: [],
    sections: ['deportes'],
    minScore: 6,
  },
  {
    tag: 'beisbol',
    strongKeywords: ['beisbol', 'campeon mundial de beisbol'],
    weakKeywords: ['vinotinto'],
    phrases: ['campeon mundial de beisbol'],
    excludePhrases: [],
    sections: ['deportes'],
    minScore: 6,
  },
  {
    tag: 'tenis',
    strongKeywords: ['tenis', 'atp', 'wta'],
    weakKeywords: ['grand slam'],
    phrases: [],
    excludePhrases: [],
    sections: ['deportes'],
    minScore: 6,
  },
  {
    tag: 'f1',
    strongKeywords: ['formula 1', 'f1', 'verstappen', 'ferrari', 'gran premio', 'liberty media'],
    weakKeywords: ['gp', 'bahrain', 'bahréin', 'arabia saudita'],
    phrases: ['gran premio'],
    excludePhrases: [],
    sections: ['deportes'],
    minScore: 6,
  },

  // Entretenimiento / lifestyle
  {
    tag: 'entretenimiento',
    strongKeywords: ['netflix', 'disney', 'masterchef', 'celebrity', 'show', 'famoso', 'actriz', 'actor', 'oscar', 'hollywood'],
    weakKeywords: ['conductora', 'plataforma', 'catalogo', 'fans', 'alfombra roja'],
    phrases: ['catalogo de netflix', 'ganadores del oscar'],
    excludePhrases: [],
    sections: ['entretenimiento'],
    minScore: 6,
  },
  {
    tag: 'cine y series',
    strongKeywords: ['pelicula', 'cine', 'serie', 'trailer', 'spider man', 'netflix'],
    weakKeywords: ['critica', 'plataforma', 'temporada'],
    phrases: ['primer trailer', '99 de aprobacion de la critica'],
    excludePhrases: [],
    sections: ['entretenimiento'],
    minScore: 6,
  },
  {
    tag: 'musica',
    strongKeywords: ['tini', 'maria becerra', 'emilia mernes', 'pop', 'cantante', 'ricardo arjona', 'angela torres', 'pink floyd', 'disco'],
    weakKeywords: ['instagram', 'redes', 'gran rex', 'entradas', 'show'],
    phrases: ['pop stars', 'the dark side of the moon'],
    excludePhrases: [],
    sections: ['entretenimiento'],
    minScore: 6,
  },
  {
    tag: 'turismo',
    strongKeywords: ['visitar', 'turismo', 'escapada', 'viajar', 'destino'],
    weakKeywords: ['fines de semana xxl', 'gastronomia', 'wanderlust'],
    phrases: ['la ciudad mas bella del mundo'],
    excludePhrases: [],
    sections: ['lifestyle'],
    regions: ['argentina'],
    minScore: 6,
  },
  {
    tag: 'salud',
    strongKeywords: ['salud', 'hospital', 'neumonia', 'obra social', 'cobertura medica'],
    weakKeywords: ['clinicas', 'medica', 'internado'],
    phrases: ['agravamiento de salud', 'hospital de aves'],
    excludePhrases: [],
    sections: ['mundo', 'nacional', 'lifestyle'],
    minScore: 6,
  },
  {
    tag: 'fauna',
    strongKeywords: ['aves', 'fauna', 'silvestre'],
    weakKeywords: ['rescate'],
    phrases: ['fauna silvestre', 'hospital de aves'],
    excludePhrases: [],
    sections: ['mundo'],
    minScore: 6,
  },

  // Autos
  {
    tag: 'autos',
    strongKeywords: ['autos', 'automotriz', 'pick up', 'motos', 'motovehiculos'],
    weakKeywords: ['vehiculos', 'patentamiento', 'transferencias', 'mercado automotor'],
    phrases: ['ventas de motos', 'nueva pick up'],
    excludePhrases: ['patentes de medicamentos'],
    sections: ['autos'],
    minScore: 6,
  },
  {
    tag: 'autos electricos',
    strongKeywords: ['autos electricos', 'baterias', 'electrificacion', 'hibrida enchufable'],
    weakKeywords: ['electrico', 'electrificados', 'autonomia electrica'],
    phrases: ['baterias para autos electricos', 'pick up hibrida enchufable'],
    excludePhrases: [],
    sections: ['autos'],
    minScore: 6,
  },
];

module.exports = TAG_RULES;
